<?php 
class about extends Jsnpdo_factory {} 
class ad_info extends Jsnpdo_factory {} 
class ad_setting extends Jsnpdo_factory {} 
class album extends Jsnpdo_factory {} 
class album_tag extends Jsnpdo_factory {} 
class article extends Jsnpdo_factory {} 
class comment extends Jsnpdo_factory {} 
class contact extends Jsnpdo_factory {} 
class extend_field extends Jsnpdo_factory {} 
class file extends Jsnpdo_factory {} 
class json_column extends Jsnpdo_factory {} 
class keys extends Jsnpdo_factory {} 
class log extends Jsnpdo_factory {} 
class loginlog extends Jsnpdo_factory {} 
class mailbox extends Jsnpdo_factory {} 
class mediabox extends Jsnpdo_factory {} 
class member extends Jsnpdo_factory {} 
class member_augp extends Jsnpdo_factory {} 
class online_visitor extends Jsnpdo_factory {} 
class popcount extends Jsnpdo_factory {} 
class power extends Jsnpdo_factory {} 
class product2 extends Jsnpdo_factory {} 
class single_page extends Jsnpdo_factory {} 
class transaction_order extends Jsnpdo_factory {} 
class transaction_transport extends Jsnpdo_factory {} 
class type_base extends Jsnpdo_factory {} 
class video extends Jsnpdo_factory {} 
class webset extends Jsnpdo_factory {} 
?>